### ISSUE TITLE
degree symbol breaks pyvtlock

### ISSUE THREAD

**Issue by fanosta** [Ferdi265/pyvtlock#1]
using a degree symbols inside the MOTD breaks the terminal where pyvtlock switches to and subsequent unlocking is no longer possible.

The tty will be blank displaying only a blinking cursor.

```bash
MOTD=° pyvtlock
```

**Comment by Ferdi265** [comment]
actually, switching back manually _was_ possible. Python crashes with an exception because of some weird unicode decode error, which results in the process exiting, which re-enables manual VT switching.

**Comment by Ferdi265** [comment]
I found the actual bug: for some reason `io.TextIOWrapper` defaulted the encoding to `ascii` instead of UTF-8 in specific circumstances.

I'll set the encoding of `nvt` to UTF-8 now, but I think we should keep the MOTD processing as bytes (some escape sequences, like `\x9b`, don't encode correctly when used in UTF-8 python strings).
